import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const origin='http://localhost:5173';
const secret=new URL((await readFile('.private/local-link.txt','utf8')).trim()).hash.slice(5);
const call=(path,body,cookie,extra={})=>fetch(origin+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{Cookie:cookie}:{}),...extra},body:body?JSON.stringify(body):undefined});
assert.equal((await call('/api/state')).status,401);
assert.equal((await call('/api/access',{key:'bad'})).status,401);
const access=await call('/api/access',{key:secret}); assert.equal(access.status,200);
const cookie=access.headers.get('set-cookie').split(';')[0];
assert.match(access.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);
const get=async()=>{const r=await call('/api/state',null,cookie);assert.equal(r.status,200);return r.json();};
let s=await get();
const envelope=(command,revision=s.revision)=>({requestId:crypto.randomUUID(),revision,command});
const send=async command=>{const r=await call('/api/command',envelope(command),cookie);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));s=await r.json();};
const created=[];
for(const name of ['API concurrent A','API concurrent B']){await send({type:'task.create',title:name,firstAction:'',basketId:'homework',day:'2026-09-28'});created.push(s.tasks.at(-1).id);}
const a=envelope({type:'session.start',taskId:created[0],switchCurrent:false});
const b=envelope({type:'session.start',taskId:created[1],switchCurrent:false});
const results=await Promise.all([call('/api/command',a,cookie),call('/api/command',b,cookie)]);
assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);
s=await get();assert(s.activeSession);
const winner=results[0].status===200?a:b;
const replay=await call('/api/command',winner,cookie);assert.equal(replay.status,200);
assert.equal((await replay.json()).revision,s.revision);
assert.equal((await call('/api/command',{...winner,command:{type:'task.archive',id:created[0]}},cookie)).status,409);
assert.equal((await call('/api/command',envelope({type:'session.pause',id:s.activeSession.id}),cookie,{Origin:'https://evil.example'})).status,403);
const snapshot=s.revision;
await send({type:'session.end',id:s.activeSession.id});
assert.equal((await call('/api/command',envelope({type:'task.archive',id:created[0]},snapshot),cookie)).status,409);
const create=envelope({type:'task.create',title:'API double tap',firstAction:'',basketId:'homework',day:'2026-09-28'});
const duplicates=await Promise.all([call('/api/command',create,cookie),call('/api/command',create,cookie)]);
assert(duplicates.every(r=>r.status===200));s=await get();
assert.equal(s.tasks.filter(t=>t.title==='API double tap'&&!t.archived).length,1);
created.push(s.tasks.at(-1).id);
for(const id of created)await send({type:'task.archive',id});
console.log('API checks passed: unauthorized access, wrong key, secure cookie, origin protection, simultaneous starts, double tap, idempotent replay, reused ID rejection, stale revision, canonical state.');
