"use client";
/* eslint-disable @next/next/no-img-element -- Local static PNGs are sized explicitly and cached by the service worker. */
import { useEffect, useRef, useState, type CSSProperties, type FormEvent } from "react";
import { BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight, CircleCheck, Clock3, Code2, FlaskConical, GraduationCap, ListChecks, MoreHorizontal, Pause, Play, Plus, Settings2, Sparkles, Trash2, TrendingUp, Undo2, WifiOff } from "lucide-react";
import { AppDialog } from "@/components/app-dialog";
import { useWorkspace } from "@/hooks/use-workspace";
import { addDays, elapsedMs, formatDuration, formatTimer, localDate, mondayOf, taskTime, weeklySummary, type Basket, type Command, type Session, type State, type Task } from "@/lib/domain";

type View = "today" | "focus" | "week" | "celebration";
type Editor = { mode: "task" | "template"; id?: string; title: string; basketId: string; day: string; firstAction: string };
type Run = (command: Command, done?: (state: State) => void) => void;
const icons = { homework: BookOpen, engineering: Code2, mathematics: GraduationCap, research: FlaskConical };
function BasketIcon({ id, size = 18 }: { id: string; size?: number }) { const Icon = icons[id as keyof typeof icons] ?? BookOpen; return <Icon size={size}/>; }
function BasketLabel({ basket }: { basket?: Basket }) { return basket ? <span className={`basket-label ${basket.color}`}><BasketIcon id={basket.id}/>{basket.name}</span> : null; }
function Mascot({ pose, className = "" }: { pose: "ready" | "training" | "celebration"; className?: string }) { return <img className={`mascot ${className}`} src={`/mascot/${pose}.png`} width="180" height="180" alt=""/>; }
function dateLabel(day: string, options: Intl.DateTimeFormatOptions = { month: "long", day: "numeric" }) { return new Date(day + "T12:00:00Z").toLocaleDateString("en-US", { ...options, timeZone: "UTC" }); }
function playCompletion(ctx: AudioContext) {
  try {
    [523.25, 659.25, 783.99].forEach((frequency, i) => { const oscillator = ctx.createOscillator(), gain = ctx.createGain(), start = ctx.currentTime + i * .11; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0, start); gain.gain.linearRampToValueAtTime(.08, start + .015); gain.gain.exponentialRampToValueAtTime(.001, start + .25); oscillator.connect(gain); gain.connect(ctx.destination); oscillator.start(start); oscillator.stop(start + .28); });
    setTimeout(() => void ctx.close(), 900);
  } catch { /* Sound is optional. */ }
}
export default function TrainingApp() {
  const [view, setView] = useState<View>("today");
  const workspace = useWorkspace(view === "focus");
  const { state, now, busy, uncertain, offline, error, command } = workspace;
  const disabled = busy || uncertain;
  const [day, setDay] = useState(() => localDate(Date.now()));
  const [week, setWeek] = useState(() => mondayOf(localDate(Date.now())));
  const [filter, setFilter] = useState("all");
  const [editor, setEditor] = useState<Editor | null>(null);
  const [menuTask, setMenuTask] = useState<Task | null>(null);
  const [switchTask, setSwitchTask] = useState<Task | null>(null);
  const [settings, setSettings] = useState(false);
  const [celebration, setCelebration] = useState<Session | null>(null);
  const [link, setLink] = useState("");
  const [wakeMessage, setWakeMessage] = useState("");
  const sound = useRef<AudioContext | null>(null);
  const active = state?.activeSession;
  useEffect(() => {
    if (!state?.preferences.keepAwake || active?.state !== "running") return;
    let lock: WakeLockSentinel | null = null, cancelled = false;
    const acquire = async () => {
      if (document.hidden || lock) return;
      if (!("wakeLock" in navigator)) { setWakeMessage("Keep awake is not available in this browser."); return; }
      try { const result = await navigator.wakeLock.request("screen"); if (cancelled) { await result.release(); return; } lock = result; result.addEventListener("release", () => { lock = null; }); setWakeMessage(""); }
      catch { setWakeMessage("Screen could not stay awake. Your timer will keep running."); }
    };
    const visibility = () => { if (document.hidden) { void lock?.release(); lock = null; } else void acquire(); };
    void acquire(); document.addEventListener("visibilitychange", visibility);
    return () => { cancelled = true; void lock?.release(); document.removeEventListener("visibilitychange", visibility); setWakeMessage(""); };
  }, [state?.preferences.keepAwake, active?.state]);
  const start = (task: Task) => {
    if (active?.taskId === task.id) { setView("focus"); return; }
    if (active) { setSwitchTask(task); return; }
    command({ type: "session.start", taskId: task.id, switchCurrent: false }, () => setView("focus"));
  };
  const openEditor = (task?: Task) => { workspace.clearError(); setMenuTask(null); setEditor(task ? { ...task, mode: "task" } : { mode: "task", title: "", firstAction: "", basketId: "homework", day }); };
  const finish = () => {
    if (!active) return;
    if (state?.preferences.sound) { try { sound.current = new AudioContext(); void sound.current.resume(); } catch { sound.current = null; } }
    command({ type: "session.finish", id: active.id }, next => { const finished = next.history.find(s => s.id === active.id); if (finished) { setCelebration(finished); setView("celebration"); if (sound.current && !document.hidden) { playCompletion(sound.current); sound.current = null; } } });
  };
  const notice = (error || offline) && <div className={`notice ${error ? "notice-error" : ""}`} role="status"><WifiOff size={18}/><span>{error || "Connection lost. Showing your last saved state; the timer keeps running."}</span><button className="text-button" disabled={busy} onClick={workspace.retry}>{busy ? "Trying…" : uncertain ? "Retry action" : "Retry"}</button></div>;
  const topbar = <header className="topbar"><button className="brand" onClick={() => setView("today")} aria-label="I Am Ronaldo, Today"><span className="brand-seven">7</span><span>i am ronaldo<span className="brand-dot">.</span></span></button>{state && <button className="icon-button" aria-label="Settings" onClick={() => setSettings(true)}><Settings2 size={22}/></button>}</header>;
  if (!state) return <div className="app-shell">{topbar}<main className="access-view"><Mascot pose="ready"/><h1>One task at a time.</h1>{workspace.access === "required" ? <><p>Open your private link to bring your tasks<br className="desktop-break"/> and progress to this device.</p><form onSubmit={e => { e.preventDefault(); void workspace.unlock(link); }}><label htmlFor="private-link">Your private link</label><input id="private-link" type="password" autoComplete="off" value={link} onChange={e => setLink(e.target.value)} placeholder="Paste your private link" required/><button className="raised green full" disabled={busy}>{busy ? "Opening…" : "Open my space"}</button></form><p className="small-label">No account needed. Keep your link to yourself.</p></> : <p role="status">{error ? "Your space is taking a little longer to load." : "Getting your space ready…"}</p>}{notice}</main></div>;
  const today = localDate(now, state.preferences.timeZone);
  const tasks = state.tasks.filter(t => !t.archived && t.day === day).sort((a,b) => a.order - b.order);
  const remaining = tasks.filter(t => t.completedAt === null);
  const completed = tasks.filter(t => t.completedAt !== null);
  const shown = remaining.filter(t => filter === "all" || t.basketId === filter);
  const activeTask = active && state.tasks.find(t => t.id === active.taskId);
  const activeBasket = state.baskets.find(b => b.id === active?.basketId);
  const progress = tasks.length ? completed.length / tasks.length * 100 : 0;
  const errorsInDialog = notice && (editor || settings || switchTask || menuTask) ? notice : null;
  return <div className="app-shell">{topbar}
    {view !== "focus" && view !== "celebration" && <nav className="tabs" aria-label="Main navigation"><button className={view === "today" ? "selected" : ""} aria-current={view === "today" ? "page" : undefined} onClick={() => setView("today")}><ListChecks size={20}/>Today</button><button className={view === "week" ? "selected" : ""} aria-current={view === "week" ? "page" : undefined} onClick={() => setView("week")}><TrendingUp size={20}/>This week</button></nav>}
    <div className="notice-wrap">{notice}</div>
    {view === "today" && <main className="today-view">
      <section className="greeting"><div><p className="eyebrow">ONE TASK AT A TIME</p><h1>Let&apos;s get a<br/>little better.</h1><p className="intro">Your goals. Your pace.</p></div><Mascot pose="ready"/></section>
      {active && <button className="resume-banner" onClick={() => setView("focus")}><span className="resume-icon">{active.state === "running" ? <Play size={19} fill="currentColor"/> : <Pause size={19}/>}</span><span><strong>{active.state === "running" ? "You're in a session" : "Your session is paused"}</strong><span>{activeTask?.title ?? active.title}</span></span><span className="resume-time">{formatTimer(elapsedMs(active,now))}</span></button>}
      <section className="daily-section" aria-label="Tasks for the selected day"><div className="section-heading day-heading"><div><h2>{day === today ? "Today's training" : dateLabel(day, { weekday: "long", month: "short", day: "numeric" })}</h2><span className="small-label">{dateLabel(day, { weekday: "long", month: "long", day: "numeric" })}</span></div><div className="date-controls"><button className="icon-button" aria-label="Previous day" onClick={() => setDay(addDays(day,-1))}><ChevronLeft size={19}/></button><label className="date-picker"><input aria-label="Choose day" type="date" value={day} onChange={e => e.target.value && setDay(e.target.value)}/></label><button className="icon-button" aria-label="Next day" onClick={() => setDay(addDays(day,1))}><ChevronRight size={19}/></button></div></div>
      {day !== today && <button className="text-button" onClick={() => setDay(today)}>Back to today</button>}
      <div className="progress-heading"><span>{tasks.length ? `${completed.length} of ${tasks.length} tasks done` : "A fresh start"}</span>{tasks.length > 0 && <span>{Math.round(progress)}%</span>}</div><div className="progress-track" role="progressbar" aria-label="Tasks completed" aria-valuemin={0} aria-valuemax={tasks.length || 1} aria-valuenow={completed.length}><div style={{width:`${progress}%`}}/></div>
      <div className="filters" aria-label="Filter by basket"><button className={`filter ${filter === "all" ? "active" : ""}`} aria-pressed={filter === "all"} onClick={() => setFilter("all")}>All</button>{state.baskets.map(b => <button key={b.id} className={`filter ${b.color} ${filter === b.id ? "active" : ""}`} aria-pressed={filter === b.id} onClick={() => setFilter(b.id)}><BasketIcon id={b.id} size={16}/>{b.name}</button>)}</div>
      <div className="task-list">{shown.map(t => { const basket = state.baskets.find(b => b.id === t.basketId); const total = taskTime(state,t.id,now); return <article className={`task-row ${active?.taskId === t.id ? "task-active" : ""}`} key={t.id}><button className="task-start" disabled={disabled} onClick={() => start(t)} aria-label={`${active?.taskId === t.id ? "Return to" : "Start"} ${t.title}`}><span className={`task-symbol ${basket?.color}`}><BasketIcon id={t.basketId} size={23}/></span><span className="task-copy"><strong>{t.title}</strong><span className="task-meta">{basket?.name}{total > 0 && <> · {formatDuration(total)}</>}</span></span><Play className="row-play" size={18}/></button><button className="task-menu" aria-label={`Options for ${t.title}`} onClick={() => setMenuTask(t)} disabled={disabled}><MoreHorizontal size={22}/></button></article>; })}</div>
      {shown.length === 0 && <div className="empty-state"><span className="empty-icon">{completed.length && !remaining.length ? <CircleCheck size={32}/> : <ListChecks size={32}/>}</span><h3>{completed.length && !remaining.length ? "Look at that progress." : filter !== "all" && remaining.length ? "Nothing in this basket yet." : "What's your first move?"}</h3><p>{completed.length && !remaining.length ? "You can rest, or choose another small step." : "Add something you want to work on.\nThe clock starts when you do."}</p></div>}
      <button className="raised green full add-task" onClick={() => openEditor()} disabled={disabled}><Plus size={21}/>{tasks.length ? "Add task" : "Add your first task"}</button>
      {completed.length > 0 && <details className="completed"><summary><span><CircleCheck size={20}/>Completed <span className="count">{completed.length}</span></span><ChevronDown size={19}/></summary><div className="completed-content">{state.baskets.map(b => { const list = completed.filter(t => t.basketId === b.id && (filter === "all" || filter === b.id)); return list.length ? <section key={b.id}><BasketLabel basket={b}/>{list.map(t => <div className="completed-row" key={t.id}><Check size={19}/><span><strong>{t.title}</strong><small>{formatDuration(taskTime(state,t.id,now))} recorded</small></span><button className="icon-button" aria-label={`Undo completion of ${t.title}`} disabled={disabled} onClick={() => command({type:"task.undo",id:t.id})}><Undo2 size={18}/></button><button className="icon-button" aria-label={`Options for ${t.title}`} onClick={() => setMenuTask(t)} disabled={disabled}><MoreHorizontal size={20}/></button></div>)}</section> : null; })}</div></details>}
      </section><p className="bottom-note">A little progress is still progress.</p>
    </main>}
    {view === "focus" && <main className="focus-view">{active ? <><Mascot pose="training"/><h1>{activeTask?.title ?? active.title}</h1><BasketLabel basket={activeBasket}/><div className={`timer ${active.state === "paused" ? "paused" : ""}`} style={{"--timer-digits":formatTimer(elapsedMs(active,now)).length} as CSSProperties} role="timer" aria-live="off" aria-label="Session elapsed time">{formatTimer(elapsedMs(active,now))}</div><p className="timer-caption">{active.state === "paused" ? "PAUSED · TAKE YOUR TIME" : "ONE TASK. YOUR OWN PACE."}</p>{activeTask?.firstAction && <p className="first-action"><span>FIRST SMALL STEP</span>{activeTask.firstAction}</p>}{state.history.some(s => s.taskId === active.taskId) && <p className="small-label task-total">Task total: {formatDuration(taskTime(state,active.taskId,now))}</p>}<div className="focus-actions"><button className="raised" disabled={disabled} onClick={() => command({type:active.state === "running" ? "session.pause" : "session.resume",id:active.id})}>{active.state === "running" ? <><Pause size={20}/>Pause</> : <><Play size={20}/>Resume</>}</button><button className="raised green" onClick={finish} disabled={disabled}><Check size={22}/>Finish task</button></div><div className="focus-secondary"><button className="text-button" disabled={disabled} onClick={() => command({type:"session.end",id:active.id}, () => setView("today"))}>End session</button><span aria-hidden="true">·</span><button className="text-button" onClick={() => setView("today")}>Back to today</button></div>{wakeMessage && <p className="small-label">{wakeMessage}</p>}</> : <div className="empty-state"><CircleCheck size={42}/><h1>Session saved.</h1><p>This session has ended, possibly on another device.</p><button className="raised green" onClick={() => setView("today")}>Back to today</button></div>}</main>}
    {view === "celebration" && celebration && <main className="celebration-view"><Mascot pose="celebration"/><span className="eyebrow">ONE MORE SMALL WIN</span><h1>You showed up.</h1><p className="intro">That&apos;s how progress happens.</p><div className="celebration-card"><CircleCheck size={28}/><h2>{state.tasks.find(t => t.id === celebration.taskId)?.title ?? celebration.title}</h2><strong className="session-duration">{formatDuration(elapsedMs(celebration,now))}</strong><span>added to</span><BasketLabel basket={state.baskets.find(b => b.id === celebration.basketId)}/></div><button className="raised green full" onClick={() => setView("today")}>Back to today</button></main>}
    {view === "week" && <WeekReview state={state} now={now} week={week} setWeek={setWeek}/>}
    {editor && <AppDialog title={editor.id ? `Edit ${editor.mode}` : editor.mode === "template" ? "New template" : "A small step forward"} close={() => setEditor(null)} locked={disabled}>{errorsInDialog}<form className="editor-form" onSubmit={(e: FormEvent) => { e.preventDefault(); const {title,firstAction,basketId,day,id,mode} = editor; if (mode === "task") command(id ? {type:"task.edit",id,title,firstAction,basketId,day} : {type:"task.create",title,firstAction,basketId,day}, () => setEditor(null)); else command(id ? {type:"template.edit",id,title,firstAction,basketId} : {type:"template.create",title,firstAction,basketId}, () => setEditor({mode:"task",title:"",firstAction:"",basketId:"homework",day})); }}>
      <fieldset disabled={disabled}><label htmlFor="task-title">What do you want to work on? <span>Optional</span></label><input autoFocus id="task-title" maxLength={200} value={editor.title} placeholder="Focus session" onChange={e => setEditor({...editor,title:e.target.value})}/><label htmlFor="task-basket">Basket</label><select id="task-basket" value={editor.basketId} disabled={!!editor.id && active?.taskId === editor.id} onChange={e => setEditor({...editor,basketId:e.target.value})}>{state.baskets.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select>{!!editor.id && active?.taskId === editor.id && <p className="field-help">End the active session before changing its basket.</p>}{editor.mode === "task" && <><label htmlFor="task-day">Day</label><input id="task-day" type="date" required value={editor.day} onChange={e => setEditor({...editor,day:e.target.value})}/></>}<label htmlFor="first-action">First small step <span>Optional</span></label><textarea id="first-action" maxLength={500} rows={2} value={editor.firstAction} placeholder="Open the assignment and choose one problem." onChange={e => setEditor({...editor,firstAction:e.target.value})}/><button className="raised green full" type="submit">{busy ? "Saving…" : editor.id ? "Save changes" : editor.mode === "template" ? "Save template" : "Add task"}</button></fieldset>
    </form>{editor.mode === "task" && !editor.id && <section className="templates"><div className="section-heading"><h3>Or start with a template</h3><button className="text-button" disabled={disabled} onClick={() => setEditor({...editor,mode:"template"})}><Plus size={16}/>New</button></div>{state.templates.map(t => <div className="template-row" key={t.id}><button className="template-add" disabled={disabled} aria-label={`Add template ${t.title}`} onClick={() => command({type:"template.add",id:t.id,day:editor.day}, () => setEditor(null))}><Plus size={18}/><span><strong>{t.title}</strong><small>{state.baskets.find(b => b.id === t.basketId)?.name}</small></span></button><button className="text-button" disabled={disabled} aria-label={`Edit template ${t.title}`} onClick={() => setEditor({...t,day:editor.day,mode:"template"})}>Edit</button></div>)}</section>}{editor.mode === "template" && editor.id && <button className="text-button danger" disabled={disabled} onClick={() => command({type:"template.delete",id:editor.id!}, () => setEditor({mode:"task",title:"",firstAction:"",basketId:"homework",day}))}><Trash2 size={17}/>Delete template</button>}</AppDialog>}
    {menuTask && <AppDialog title="Task options" close={() => setMenuTask(null)} locked={disabled}>{errorsInDialog}<p className="menu-title">{menuTask.title}</p><div className="menu-actions"><button className="raised" disabled={disabled} onClick={() => openEditor(menuTask)}>Edit task or change day</button>{menuTask.completedAt === null && <><button className="raised" disabled={disabled || remaining[0]?.id === menuTask.id} onClick={() => { const index = remaining.findIndex(t => t.id === menuTask.id), ids = remaining.map(t => t.id); [ids[index-1],ids[index]] = [ids[index],ids[index-1]]; command({type:"task.reorder",ids,day}, () => setMenuTask(null)); }}>Move up</button><button className="raised" disabled={disabled || remaining.at(-1)?.id === menuTask.id} onClick={() => { const index = remaining.findIndex(t => t.id === menuTask.id), ids = remaining.map(t => t.id); [ids[index+1],ids[index]] = [ids[index],ids[index+1]]; command({type:"task.reorder",ids,day}, () => setMenuTask(null)); }}>Move down</button></>}<button className="raised danger" disabled={disabled || active?.taskId === menuTask.id} onClick={() => command({type:"task.archive",id:menuTask.id}, () => setMenuTask(null))}><Trash2 size={18}/>Delete task</button><p className="field-help">Recorded time stays in your weekly review.{active?.taskId === menuTask.id && " End the session before deleting this task."}</p></div></AppDialog>}
    {switchTask && <AppDialog title="One task at a time" close={() => setSwitchTask(null)} locked={disabled}>{errorsInDialog}<p>You already have a session for <strong>{activeTask?.title ?? active?.title}</strong>.</p><div className="menu-actions"><button className="raised green" disabled={disabled} onClick={() => { setSwitchTask(null); setView("focus"); }}>Resume current session</button><button className="raised" disabled={disabled} onClick={() => command({type:"session.start",taskId:switchTask.id,switchCurrent:true}, () => { setSwitchTask(null); setView("focus"); })}>End current & start this task</button></div></AppDialog>}
    {settings && <AppDialog title="Make it yours" close={() => setSettings(false)} locked={disabled}>{errorsInDialog}<Settings state={state} command={command} disabled={disabled}/></AppDialog>}
  </div>;
}
function Settings({ state, command, disabled }: { state: State; command: Run; disabled: boolean }) {
  const [names,setNames] = useState<Record<string,string>>({});
  const [name,setName] = useState("");
  const [color,setColor] = useState<"blue"|"purple"|"orange"|"green"|"pink"|"teal">("blue");
  const update = (field: "sound" | "keepAwake", value: boolean) => command({type:"preferences.update",...state.preferences,[field]:value});
  return <div className="settings"><h3>Your focus space</h3><label className="toggle-row"><span><strong>Completion sound</strong><small>A little celebration while the app is open.</small></span><input type="checkbox" checked={state.preferences.sound} disabled={disabled} onChange={e => update("sound",e.target.checked)}/></label><label className="toggle-row"><span><strong>Keep screen awake</strong><small>While your timer runs and the app is visible.</small></span><input type="checkbox" checked={state.preferences.keepAwake} disabled={disabled} onChange={e => update("keepAwake",e.target.checked)}/></label><p className="field-help">Weeks run Monday–Sunday in Indianapolis time.</p><h3>Your baskets</h3>{state.baskets.map(b => <form className="basket-edit" key={b.id} onSubmit={e => { e.preventDefault(); command({type:"basket.rename",id:b.id,name:names[b.id] ?? b.name}); }}><span className={`task-symbol ${b.color}`}><BasketIcon id={b.id}/></span><input aria-label={`Rename ${b.name}`} required maxLength={40} value={names[b.id] ?? b.name} onChange={e => setNames({...names,[b.id]:e.target.value})}/><button className="text-button" disabled={disabled || names[b.id] === undefined || names[b.id] === b.name}>Save</button></form>)}<form className="new-basket" onSubmit={e => { e.preventDefault(); command({type:"basket.create",name,color}, () => setName("")); }}><label htmlFor="basket-name">Add a basket</label><input id="basket-name" value={name} onChange={e => setName(e.target.value)} required maxLength={40} placeholder="Basket name"/><div className="form-pair"><label>Color<select value={color} onChange={e => setColor(e.target.value as typeof color)}>{["blue","purple","orange","green","pink","teal"].map(c => <option key={c} value={c}>{c}</option>)}</select></label><button className="raised" disabled={disabled || !name.trim()}><Plus size={18}/>Add basket</button></div></form><section className="home-screen"><h3>A home for your small wins</h3><p>On iPhone, open your private link in Safari. Tap Share, then <strong>Add to Home Screen</strong>.</p><p>If your tasks don&apos;t appear in the installed app, paste your private link once to remember this device.</p><p className="field-help">Your timer keeps running when you close the app. Sound plays only while it is open. Anyone with your private link can view and change your tasks.</p></section></div>;
}
function WeekReview({ state, now, week, setWeek }: { state: State; now: number; week: string; setWeek: (week: string) => void }) {
  const [selected,setSelected] = useState<string|null>(null);
  const summary = weeklySummary(state,week,now), total = summary.reduce((sum,b) => sum+b.ms,0);
  const currentWeek = mondayOf(localDate(now,state.preferences.timeZone));
  const basket = summary.find(b => b.id === selected);
  const grouped = basket ? Array.from(new Set(basket.items.map(s => s.taskId))).map(id => ({id,task:state.tasks.find(t => t.id === id),items:basket.items.filter(s => s.taskId === id)})) : [];
  return <main className="week-view"><p className="eyebrow">THE WORK ADDS UP</p><h1>Your week in focus.</h1><p className="intro">A look at where your time went.</p><div className="week-navigation"><button className="icon-button" aria-label="Previous week" onClick={() => setWeek(addDays(week,-7))}><ChevronLeft size={20}/></button><strong>{dateLabel(week,{month:"short",day:"numeric"})} – {dateLabel(addDays(week,6),{month:"short",day:"numeric",year:"numeric"})}</strong><button className="icon-button" aria-label="Next week" onClick={() => setWeek(addDays(week,7))}><ChevronRight size={20}/></button></div>{week !== currentWeek && <button className="text-button" onClick={() => setWeek(currentWeek)}>Back to this week</button>}<section className="weekly-total"><span className="total-icon"><Clock3 size={26}/></span><div><strong>{formatDuration(total)}</strong><span>Total time recorded</span></div></section>{total === 0 ? <div className="empty-state"><Sparkles size={32}/><h3>A little time goes a long way.</h3><p>No time recorded this week yet.<br/>Your sessions will appear here as you go.</p></div> : <><div className="basket-chart" aria-label="Weekly time by basket">{summary.map(b => <button key={b.id} className={`chart-row ${selected === b.id ? "expanded" : ""}`} aria-expanded={selected === b.id} onClick={() => setSelected(selected === b.id ? null : b.id)}><div className="chart-label"><BasketLabel basket={b}/><span><strong>{formatDuration(b.ms)}</strong><small>{(b.ms/total*100).toFixed(1)}%</small></span></div><div className="chart-track"><div className={`chart-fill ${b.color}`} style={{width:`${b.ms/total*100}%`}}/></div></button>)}</div><p className="field-help">Includes unfinished work and running sessions. Pauses aren&apos;t counted. Choose a basket to see the details.</p></>}{basket && total > 0 && <section className="week-details"><h2>{basket.name}</h2>{grouped.length ? grouped.map(g => <details key={g.id} className="session-group"><summary><span><strong>{g.task?.title ?? g.items[0].title}</strong><small>{g.task?.completedAt ? "Completed" : "In progress"}{g.task?.archived ? " · Deleted task" : ""} · {g.items.length} {g.items.length === 1 ? "session" : "sessions"}</small></span><strong>{formatDuration(g.items.reduce((sum,s) => sum+s.weekMs,0))}</strong></summary><div>{g.items.map(s => <div className="session-detail" key={s.id}><span>{new Date(s.startedAt).toLocaleString("en-US",{timeZone:state.preferences.timeZone,month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}<small>{s.state === "running" ? "Running" : s.state === "paused" ? "Paused" : s.outcome === "completed" ? "Task finished" : "Session ended"}</small></span><strong>{formatDuration(s.weekMs)}</strong></div>)}</div></details>) : <p className="intro">No time in this basket this week.</p>}</section>}<p className="bottom-note">Your time is a reflection, not a score.</p></main>;
}


